name: Deploy latest docs

on:
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: |
          cd retrofit
          dart doc
          mv doc/api ../public
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
